# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:
  - name: launching AWS instance using Ansible
    ec2:
      key_name: ansible
      instance_type: t2.micro
      image: ami-09e67e426f25ce0d7
      region: us-east-1
      wait: yes
      group: ansible
      count: 1
      vpc_subnet_id: subnet-05a3f12c93e6692f1
      assign_public_ip: yes
      aws_access_key: ASIAXGLWUMQR2VDUNMGZ
      aws_secret_key: ZLCOR55sxlw4MPHdt+lK0m0KSoOAb77fkTMjnhKn
      security_token: FwoGZXIvYXdzENX//////////wEaDKs/vQjmeHNnvkVqriKzAW2dvZq/fPiWCH+ZyJKEjeOpim6fddzUeqB+IZw7qS3Qn0dbNCTdt1K2weTMQhOCovsDRJGEnIet/5aF4Z7U3x/dlzOdZygMlChqdB7W2W6DsMzRVHqIE986ZVbdZ6iyYu5LqbHRmKVLWMOqlYycgqnNq80J84FxwpWV9KCx2+EmPAW6ZTPhn3Dm8CGMdG349PdtZg3nsdOFMZdd3c8+PmOAhHqkckOkFZ8neGrT4oiEvgazKPWs+YkGMi1uaD0rHdPLbxT/UantB8rN91ceoeXechKexeJBVEuEBApbvUCXNoSo9VPZCOg=
